version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dbProject
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud
      MYSQL_USER: project_crud
      MYSQL_PASSWORD: root
    volumes:
      - db_project_data:/var/lib/mysql
    ports:
      - "3309:3306"

volumes:
  db_project_data: {}
